version: "3.8"

services:
  lic_server:
    build:
      context: src/Pyalic_Server
      dockerfile: Dockerfile
      target: prod
    env_file: .env
    environment:
      DB_HOST: postgresql:5432
      DB_USER: lic_server
      DB_PASSWORD: "${DB_PASSWORD:-db_password}"
      DB_NAME: advanced_lic

      SECRET_KEY: "${SECRET_KEY:-8e0fb2cd6ad5b277d6f24def8c2f2f62dff9a9c0996d4c44d957419cea5b1dc2}"

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD:-redis_password}"
      REDIS_DB: 1

      DEFAULT_USER: "${DEFAULT_USER:-user}"
      DEFAULT_PASSWORD: "${DEFAULT_PASSWORD:-changeme}"

      SESSION_ALIVE_PERIOD: 4
    expose:
      - 8000
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    build: src/nginx
    ports:
      - "8000:80"
      - "5443:443"
    depends_on:
      - lic_server
    volumes:
      - /etc/ssl/lic_server:/etc/ssl/lic_server

  postgresql:
    image: "postgres:15-alpine"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_USER: lic_server
      POSTGRES_PASSWORD: "${DB_PASSWORD:-db_password}"
      POSTGRES_DB: advanced_lic
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lic_server -d advanced_lic" ]
      timeout: 5s
      interval: 2s
      retries: 3

  redis:
    image: "redis:alpine"
    expose:
      - 6379
    restart: always
    volumes:
      - redis_data:/data
    env_file: .env
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD:-redis_password}"
    command: redis-server --save 1 30 --loglevel warning --requirepass "${REDIS_PASSWORD}"

volumes:
  postgres_data:
  redis_data: